import logging
import sqlglot
from sqlglot import exp

from engine.models import DataSource
from engine.errors import DataBoxError

logger = logging.getLogger("databox.policy")

class PolicyEngine:
    @staticmethod
    def enforce_query_policy(ds: DataSource, sql_str: str, policy: str = "user_readonly") -> None:
        """
        Enforces read-only and environment policies on raw query execution.

        Workbench operations (table_preview, schema_introspection, explain)
        use backend-generated SQL and skip AST parsing — the caller is
        trusted because the SQL is generated by DataBox, not user or model.
        """
        # Workbench-generated SQL — skip parsing, trust the system
        if policy in {"table_preview", "schema_introspection", "explain"}:
            return

        if not ds.is_read_only and ds.env != "prod":
            return  # Fast path: development database and writable

        # Parse AST to identify commands
        # Resolve dialect so that MySQL backtick-quoted identifiers
        # (e.g. `orders`) are correctly parsed instead of triggering
        # POLICY_PARSE_ERROR.
        sqlglot_dialect: str = "mysql"
        db_type = (ds.db_type or "mysql").lower()
        if "postgres" in db_type:
            sqlglot_dialect = "postgres"
        elif "sqlite" in db_type:
            sqlglot_dialect = "sqlite"
        try:
            expressions = sqlglot.parse(sql_str, read=sqlglot_dialect)
        except Exception as exc:
            logger.warning("SQL parsing failed in PolicyEngine; blocking query: %s", exc)
            raise DataBoxError(
                code="POLICY_PARSE_ERROR",
                message=f"SQL 无法被安全策略引擎解析，已按潜在注入风险阻断。数据源: '{ds.name}'。"
            ) from exc

        # Walk AST to detect mutations
        mutations = (
            exp.Insert, exp.Update, exp.Delete, exp.Drop, exp.Create, exp.Alter, exp.Command, exp.Merge
        )

        for expr in expressions:
            if not expr:
                continue
            for node in expr.walk():
                if isinstance(node, mutations):
                    # Check Read-Only restriction
                    if ds.is_read_only:
                        raise DataBoxError(
                            code="READ_ONLY_VIOLATION",
                            message=f"数据源 '{ds.name}' 处于只读防护模式下，禁止执行写入/修改/定义 SQL (指令类型: {type(node).__name__})。"
                        )
                    # Check Production restriction (for safety, restrict DDL in prod)
                    if ds.env == "prod" and isinstance(node, (exp.Drop, exp.Create, exp.Alter)):
                        raise DataBoxError(
                            code="PROD_POLICY_VIOLATION",
                            message=f"数据源 '{ds.name}' 属于生产环境，已被 Policy 引擎安全锁定，拒绝通过此处执行结构定义变更 (DDL: {type(node).__name__})。"
                        )

    @staticmethod
    def enforce_ddl_policy(ds: DataSource) -> None:
        """
        Explicit check before table designer executing generated DDL.
        """
        if ds.is_read_only:
            raise DataBoxError(
                code="READ_ONLY_VIOLATION",
                message=f"数据源 '{ds.name}' 已开启只读保护，禁止执行任何结构变更变更 DDL。"
            )
        if ds.env == "prod":
            raise DataBoxError(
                code="PROD_POLICY_VIOLATION",
                message=f"数据源 '{ds.name}' 属于生产环境 (Production)，安全策略禁止通过桌面客户端直接执行结构修改/建表 DDL。"
            )

    @staticmethod
    def enforce_test_data_policy(ds: DataSource) -> None:
        """
        Checks before spawning fake test data.
        """
        if ds.is_read_only:
            raise DataBoxError(
                code="READ_ONLY_VIOLATION",
                message=f"数据源 '{ds.name}' 处于只读防护模式下，禁止生成测试数据。"
            )
        if ds.env == "prod":
            raise DataBoxError(
                code="PROD_POLICY_VIOLATION",
                message=f"数据源 '{ds.name}' 属于生产环境 (Production)，已被安全 Policy 引擎拦截：禁止在生产环境生成测试数据。"
            )

    @staticmethod
    def enforce_restore_policy(ds: DataSource) -> None:
        """
        Checks before database restore recovery actions.
        """
        if ds.is_read_only:
            raise DataBoxError(
                code="RESTORE_READONLY_ERROR",
                message=f"数据源 '{ds.name}' 处于只读模式下，禁止执行数据库覆盖还原操作。"
            )
        if ds.env == "prod":
            # In a production context, restore is a catastrophic operation if done casually
            raise DataBoxError(
                code="PROD_POLICY_VIOLATION",
                message=f"拒绝操作：数据源 '{ds.name}' 属于生产环境 (Production)，Policy 引擎默认禁止对其执行覆盖还原 (Restore) 操作。"
            )
