import type { ProductAssets } from "./types";

export const databoxProductAssets = {
  brand: {
    name: "DataBox",
    tagline: "本地优先的 AI 数据库工作台",
    oneLiner: "连接数据源、理解 Schema、生成 SQL、审计执行，一切都在可信的本地边界内完成。",
    keywords: ["local-first", "AI-native", "database workbench", "TrustGate", "SQL Agent", "Schema Explorer"],
  },

  hero: {
    eyebrow: "AI Native Database Workbench",
    title: "让每一次问数都可解释、可审批、可回滚",
    subtitle: "DataBox 把数据库工作台、SQL 控制台和问数 Agent 放进同一个桌面应用。",
    description: "面向分析师、开发者和数据团队：先连接本地数据源，理解表结构和语义，再让 Agent 生成 SQL、解释结果，并在策略层和 TrustGate 保护下执行高风险操作。",
    primaryCta: {
      label: "连接第一个数据源",
      variant: "primary",
      action: "open.datasource.create",
      helperText: "支持 MySQL、PostgreSQL、SQLite。",
    },
    secondaryCta: {
      label: "体验问数工作台",
      variant: "secondary",
      action: "open.smartQuery",
      helperText: "使用示例问题快速看到 Agent 工作流。",
    },
    proofPoints: [
      "本地 Engine 运行在 127.0.0.1，前端通过本地 Token 访问",
      "所有 SQL 执行先经过策略层和 TrustGate",
      "Agent 事件、产物、审批和 Trace 可观测",
      "内置评测入口，持续验证真实 Schema 下的可靠性",
    ],
  },

  personas: [
    {
      id: "analyst",
      name: "业务分析师",
      role: "把自然语言问题变成可信指标",
      pain: "知道要问什么，但不想每次都从复杂表结构和 JOIN 开始。",
      outcome: "直接选表发问，得到 SQL、结果解释、后续追问和可复核的分析链路。",
      defaultPrompt: "上个月各渠道新增用户和付费转化率分别是多少？按渠道降序展示。",
      recommendedEntry: "问数工作台",
    },
    {
      id: "developer",
      name: "后端 / 数据开发者",
      role: "快速理解库表并安全调试查询",
      pain: "临时排查问题时需要频繁查看 Schema、写 SQL、解释执行计划。",
      outcome: "在同一工作区浏览表字段、校验 SQL、执行 EXPLAIN，并保留查询历史。",
      defaultPrompt: "帮我检查这段 SQL 为什么扫描了全表，并给出索引建议。",
      recommendedEntry: "SQL 控制台",
    },
    {
      id: "data-lead",
      name: "数据负责人",
      role: "让团队在安全边界内使用 AI 问数",
      pain: "AI 生成 SQL 容易越权、误改数据或输出不可追溯结论。",
      outcome: "通过策略层、审批、Trace 和评测，把 Agent 能力纳入可治理流程。",
      defaultPrompt: "查看最近 10 次 Agent 运行中有哪些进入人工审批，原因是什么？",
      recommendedEntry: "Agent 评测",
    },
  ],

  features: [
    {
      id: "datasource-workbench",
      icon: "Database",
      title: "数据源与 Schema 工作台",
      subtitle: "从连接到理解，一站完成",
      description: "管理 MySQL、PostgreSQL、SQLite 连接，测试健康状态，同步 Schema，并浏览表、字段和关系图数据。",
      bullets: ["连接测试与健康检查", "Schema 同步和表字段浏览", "数据源删除二次确认", "适配直连、SSH 隧道和 SSL 配置"],
      badge: "基础工作流",
      cta: { label: "管理数据源", variant: "secondary", action: "open.datasource.manager" },
    },
    {
      id: "sql-console",
      icon: "Terminal",
      title: "安全 SQL 控制台",
      subtitle: "写 SQL，但不裸奔到数据库",
      description: "SQL 校验、执行、EXPLAIN、取消执行和历史检索都通过统一策略层处理，降低误操作风险。",
      bullets: ["执行前校验与策略检查", "EXPLAIN 辅助性能分析", "历史按数据源、状态、关键字过滤", "限制结果体量，保护桌面 UI"],
      badge: "Power User",
      cta: { label: "打开 SQL 控制台", variant: "primary", action: "open.sqlConsole" },
    },
    {
      id: "ai-agent",
      icon: "Sparkles",
      title: "对话式问数 Agent",
      subtitle: "从问题到 SQL、结果和解释",
      description: "Agent 读取当前数据源、选中表、Schema、语义上下文和历史对话，生成可审计的问数过程。",
      bullets: ["自然语言问数", "SQL 生成与修复", "结果解释与追问建议", "SSE 事件驱动的前端时间线"],
      badge: "AI 原生",
      cta: { label: "开始问数", variant: "primary", action: "open.smartQuery" },
    },
    {
      id: "trustgate",
      icon: "ShieldCheck",
      title: "TrustGate 执行边界",
      subtitle: "先验证，再执行；必要时人工确认",
      description: "高风险 SQL 或敏感工具调用会进入审批卡片，用户确认后 Agent 才会继续执行。",
      bullets: ["风险等级与原因提示", "审批通过 / 拒绝 / 修改", "测试绕过限制在开发场景", "运行轨迹可追溯"],
      badge: "安全模型",
      cta: { label: "查看审批记录", variant: "ghost", action: "open.agent.approvals" },
    },
    {
      id: "agent-observability",
      icon: "Workflow",
      title: "Agent 可观测性",
      subtitle: "把黑盒推理变成可复盘链路",
      description: "计划、工具调用、产物、Trace、Checkpoint 和审批记录都可以在前端工作区中呈现。",
      bullets: ["运行时间线", "结构化 Artifacts", "失败上下文和修复状态", "会话历史持久化"],
      badge: "可复盘",
    },
    {
      id: "agent-eval",
      icon: "FlaskConical",
      title: "Agent 评测入口",
      subtitle: "能力升级要有回归基线",
      description: "维护评测任务、导入 benchmark、运行评测并查看 case，让 Agent 在真实 Schema 下持续变稳。",
      bullets: ["评测任务管理", "Benchmark 导入", "Run 与 Case 查看", "适合团队持续回归"],
      badge: "团队治理",
      cta: { label: "打开 Agent 评测", variant: "secondary", action: "open.agentEval" },
    },
  ],

  workflow: [
    {
      id: "connect",
      step: 1,
      title: "连接本地或内网数据源",
      description: "创建 MySQL、PostgreSQL 或 SQLite 数据源，完成连接测试和健康检查。",
      surface: "datasource",
      successState: "左侧树出现可用数据源和库表列表。",
    },
    {
      id: "understand-schema",
      step: 2,
      title: "同步并理解 Schema",
      description: "浏览表、字段、关系和语义信息，把关键表加入上下文。",
      surface: "schema",
      successState: "工作区获得已选表和字段上下文。",
    },
    {
      id: "ask-agent",
      step: 3,
      title: "用自然语言发起问数",
      description: "输入业务问题，Agent 会规划任务、读取上下文并生成 SQL 或分析步骤。",
      surface: "agent",
      successState: "前端时间线显示计划、工具调用和产物更新。",
    },
    {
      id: "approve-risk",
      step: 4,
      title: "遇到高风险动作先审批",
      description: "涉及写入、删除、跨范围或不确定 SQL 时，TrustGate 会要求人工确认。",
      surface: "approval",
      successState: "审批卡片展示风险等级、原因和 SQL 预览。",
    },
    {
      id: "inspect-result",
      step: 5,
      title: "查看结果、解释和追问",
      description: "获得结构化答案、图表建议、SQL 结果和后续分析方向。",
      surface: "history",
      successState: "问数结果被保存到对话历史，可继续追问或复盘。",
    },
    {
      id: "evaluate",
      step: 6,
      title: "用评测闭环 Agent 质量",
      description: "把真实问题沉淀成 case，持续验证 SQL 生成、修复和解释能力。",
      surface: "eval",
      successState: "评测任务产生 run 和 case 结果。",
    },
  ],

  onboarding: [
    {
      id: "setup-llm",
      title: "配置 LLM Provider",
      description: "填写 OpenAI-compatible Base URL、API Key 和模型名称。未配置时 Agent 会明确提示。",
      actionLabel: "配置 LLM",
      targetRoute: "llm-config",
      completionSignal: "llm.connection.ok",
      emptyStateCopy: "还没有可用模型。先完成 LLM 配置，再让 Agent 生成 SQL。",
    },
    {
      id: "create-datasource",
      title: "添加第一个数据源",
      description: "选择数据库类型，填写连接信息，运行连接测试并保存。",
      actionLabel: "新建数据源",
      targetRoute: "datasource-settings",
      completionSignal: "datasource.created",
      emptyStateCopy: "还没有数据源。DataBox 需要先连接数据库，才能读取 Schema 和问数。",
    },
    {
      id: "sync-schema",
      title: "同步 Schema 元数据",
      description: "同步表、字段、关系和基础统计信息，为 Agent 提供可靠上下文。",
      actionLabel: "同步 Schema",
      targetRoute: "schema-tree",
      completionSignal: "schema.synced",
      emptyStateCopy: "数据源已连接，但还没有 Schema。同步后可开始浏览表结构。",
    },
    {
      id: "run-first-question",
      title: "发起第一次问数",
      description: "从示例问题开始，观察 Agent 的计划、SQL、审批和结果解释。",
      actionLabel: "试试示例问题",
      targetRoute: "smart-query",
      completionSignal: "agent.run.completed",
      emptyStateCopy: "选择一张表或使用示例问题，开启第一次可审计问数。",
    },
  ],

  prompts: [
    {
      id: "monthly-assets",
      label: "上月资产发布量",
      prompt: "帮我查一下“市场运营部”上个月发布了多少资产？按资产类型拆分，并给出环比变化。",
      intent: "ask",
      requiredContext: ["部门表", "资产表", "发布时间字段"],
      exampleResult: "输出资产总数、类型分布、环比变化和对应 SQL。",
    },
    {
      id: "conversion-funnel",
      label: "转化漏斗分析",
      prompt: "统计近 30 天从注册、激活到付费的漏斗转化率，并指出下降最明显的环节。",
      intent: "compare",
      requiredContext: ["用户表", "行为事件表", "订单表"],
      exampleResult: "输出各环节人数、转化率、异常环节和后续排查建议。",
    },
    {
      id: "slow-query",
      label: "慢 SQL 排查",
      prompt: "解释这段 SQL 为什么慢，先给出 EXPLAIN 思路，再建议如何改写或增加索引。",
      intent: "explain",
      requiredContext: ["SQL 文本", "表字段", "索引信息"],
      exampleResult: "输出风险点、可能原因、改写 SQL 和索引建议。",
    },
    {
      id: "risk-audit",
      label: "高风险操作审计",
      prompt: "检查最近 20 次 Agent 运行里哪些 SQL 进入了人工审批，并按风险等级分组。",
      intent: "audit",
      requiredContext: ["Agent Run", "审批记录", "Trace"],
      exampleResult: "输出审批次数、风险原因 TopN、涉及表和处理状态。",
    },
    {
      id: "sql-repair",
      label: "SQL 修复",
      prompt: "这段 SQL 报错了：字段不存在。请根据当前 Schema 修复 SQL，并说明修复依据。",
      intent: "repair",
      requiredContext: ["错误信息", "当前 Schema", "原 SQL"],
      exampleResult: "输出修复后的 SQL、字段映射说明和验证步骤。",
    },
    {
      id: "table-profile",
      label: "表画像",
      prompt: "给 orders 表做一个快速画像：行数、关键字段、可能的时间字段、可用于分析的维度和指标。",
      intent: "ask",
      requiredContext: ["目标表", "字段信息", "样本统计"],
      exampleResult: "输出表用途推断、字段分组、可用指标和推荐问题。",
    },
  ],

  emptyStates: [
    {
      id: "no-datasource",
      surface: "datasource",
      title: "还没有数据源",
      description: "连接一个 MySQL、PostgreSQL 或 SQLite 数据库，DataBox 才能同步 Schema 并提供问数上下文。",
      primaryAction: { label: "新建数据源", variant: "primary", action: "open.datasource.create" },
      secondaryAction: { label: "查看连接说明", variant: "ghost", action: "open.docs.datasource" },
      tips: ["建议使用只读账号开始体验", "生产库请确认网络、SSL 和 SSH 隧道策略", "保存前先运行连接测试"],
    },
    {
      id: "no-schema",
      surface: "schema",
      title: "等待同步 Schema",
      description: "数据源已连接，但还没有可浏览的表结构。同步后可以打开表工作区、SQL 控制台和 Agent 问数。",
      primaryAction: { label: "同步 Schema", variant: "primary", action: "schema.sync" },
      tips: ["同步会读取表和字段元数据", "字段越完整，Agent 生成 SQL 越可靠", "可在同步后选择关键表加入上下文"],
    },
    {
      id: "no-agent-context",
      surface: "agent",
      title: "先选择一个数据源或表",
      description: "Agent 需要当前数据源、表结构和语义上下文，才能生成可验证 SQL。",
      primaryAction: { label: "选择数据源", variant: "secondary", action: "focus.datasource.tree" },
      tips: ["选中 1 到 3 张关键表效果更好", "问题中尽量包含时间范围和口径", "高风险 SQL 会进入审批"],
    },
    {
      id: "no-history",
      surface: "history",
      title: "还没有对话历史",
      description: "完成一次问数后，问题、回答、产物和上下文会保存在本地，方便继续追问和复盘。",
      primaryAction: { label: "开始第一次问数", variant: "primary", action: "open.smartQuery" },
      tips: ["历史保存在本地", "可以从历史重新打开结果页", "适合沉淀常用分析问题"],
    },
    {
      id: "no-eval-task",
      surface: "eval",
      title: "还没有评测任务",
      description: "把真实业务问题沉淀成评测任务，验证 Agent 在当前 Schema 下的 SQL 生成、修复和解释质量。",
      primaryAction: { label: "创建评测任务", variant: "primary", action: "agentEval.task.create" },
      secondaryAction: { label: "导入 Benchmark", variant: "secondary", action: "agentEval.importBenchmark" },
      tips: ["建议覆盖高频问题和复杂 JOIN", "评测结果可作为升级前后的回归基线", "失败 case 可反向完善语义层"],
    },
  ],

  trustSignals: [
    {
      id: "local-engine",
      icon: "Lock",
      label: "本地 Engine",
      value: "127.0.0.1:18625",
      description: "桌面前端只访问本地 FastAPI Engine，不把数据库连接交给远端服务。",
      tone: "security",
    },
    {
      id: "token-gate",
      icon: "ShieldCheck",
      label: "本地 Token",
      value: "X-Local-Token",
      description: "Engine 启动时生成本地访问令牌，前端请求必须携带。",
      tone: "security",
    },
    {
      id: "trustgate",
      icon: "AlertTriangle",
      label: "策略门控",
      value: "Policy + TrustGate",
      description: "SQL 执行前经过安全检查、范围检查和人工审批判断。",
      tone: "expert",
    },
    {
      id: "observable-agent",
      icon: "Workflow",
      label: "可观测 Agent",
      value: "Events / Trace / Artifacts",
      description: "Agent 的计划、工具调用、产物和审批都可以被前端呈现。",
      tone: "calm",
    },
  ],

  demoScenarios: [
    {
      id: "marketing-assets-monthly",
      title: "市场运营部资产发布分析",
      industry: "内容运营 / 企业知识库",
      userQuestion: "市场运营部上个月发布了多少资产？按资产类型拆分，并找出增长最快的类型。",
      tables: ["departments", "assets", "asset_publish_logs"],
      agentPlan: [
        "识别部门名称并确认部门 ID",
        "确定上个月的自然月时间范围",
        "按资产类型聚合发布数量并计算环比",
        "生成结果解释和后续追问建议",
      ],
      safeSqlPreview: "SELECT asset_type, COUNT(*) AS published_count FROM assets WHERE department_name = '市场运营部' AND published_at >= :month_start AND published_at < :month_end GROUP BY asset_type ORDER BY published_count DESC;",
      insightCards: [
        { id: "total", label: "发布资产", value: "428", delta: "+18.4% MoM", caption: "较上月增长 67 个", tone: "good" },
        { id: "top-type", label: "Top 类型", value: "活动素材", delta: "占比 41%", caption: "增长主要来自活动复盘包", tone: "neutral" },
        { id: "risk", label: "需复核", value: "12", delta: "字段缺失", caption: "缺少完整资产类型，建议补齐口径", tone: "warning" },
      ],
      followUps: ["这些资产主要由哪些成员发布？", "按周拆分是否存在集中发布？", "资产发布量和下载量之间是否相关？"],
    },
    {
      id: "orders-funnel",
      title: "订单转化漏斗排查",
      industry: "电商 / SaaS 增长",
      userQuestion: "近 30 天注册到首单转化率下降了吗？请拆到渠道维度。",
      tables: ["users", "user_events", "orders", "channels"],
      agentPlan: [
        "确定注册、激活、下单事件口径",
        "按渠道聚合漏斗人数",
        "计算环比和下降幅度",
        "标记样本过小或口径不一致的渠道",
      ],
      safeSqlPreview: "WITH registered AS (...) SELECT channel_name, registered_users, activated_users, first_order_users, first_order_users * 1.0 / NULLIF(registered_users, 0) AS conversion_rate FROM funnel_by_channel ORDER BY conversion_rate ASC;",
      insightCards: [
        { id: "conversion", label: "首单转化", value: "7.8%", delta: "-1.6pp", caption: "低于前 30 天", tone: "warning" },
        { id: "worst-channel", label: "下降渠道", value: "paid_search", delta: "-3.4pp", caption: "需要排查投放质量", tone: "danger" },
        { id: "sample", label: "有效样本", value: "18,240", delta: "+6.1%", caption: "样本量充足", tone: "good" },
      ],
      followUps: ["按投放 campaign 再拆一层", "只看新用户首单转化", "对比激活后的 7 日留存"],
    },
    {
      id: "sql-safety-review",
      title: "高风险 SQL 审批演示",
      industry: "平台治理 / 数据安全",
      userQuestion: "帮我删除 90 天前的临时订单数据。",
      tables: ["orders_temp", "approval_records", "query_history"],
      agentPlan: [
        "识别 DELETE 操作为高风险动作",
        "生成影响范围预估 SQL",
        "进入 TrustGate 人工审批",
        "审批通过后才继续执行或建议改为备份流程",
      ],
      safeSqlPreview: "SELECT COUNT(*) AS affected_rows FROM orders_temp WHERE created_at < :cutoff_date;",
      insightCards: [
        { id: "risk-level", label: "风险等级", value: "High", delta: "需要审批", caption: "DELETE 操作不会自动执行", tone: "danger" },
        { id: "affected", label: "预计影响", value: "31,842", delta: "仅预估", caption: "先展示 SELECT 预检查", tone: "warning" },
        { id: "fallback", label: "建议动作", value: "先备份", delta: "可回滚", caption: "生成备份与恢复检查", tone: "neutral" },
      ],
      followUps: ["先生成备份 SQL", "只删除已归档状态的数据", "查看类似审批历史"],
    },
  ],

  releaseHighlights: [
    {
      id: "workspace-tabs",
      title: "多工作区 Tabs",
      description: "问数、表浏览、SQL 控制台、数据源管理和 Agent 评测都可以作为工作区标签打开。",
      tags: ["Desktop UX", "Workspace"],
    },
    {
      id: "streaming-agent-timeline",
      title: "Agent 流式时间线",
      description: "前端通过 SSE 接收运行事件，把计划、工具调用、产物和审批状态持续同步到结果页。",
      tags: ["Agent", "SSE", "Observability"],
    },
    {
      id: "conversation-history",
      title: "本地对话历史",
      description: "问数结果、消息、上下文表和 Artifacts 可在本地历史中复盘并继续追问。",
      tags: ["SQLite", "History"],
    },
    {
      id: "agent-eval-loop",
      title: "Agent 评测闭环",
      description: "从真实业务问题中沉淀 benchmark，让每次 Prompt、语义层和工具改造都有回归依据。",
      tags: ["Eval", "Quality"],
    },
  ],

  faq: [
    {
      id: "cloud-or-local",
      question: "DataBox 会把数据库连接交给云端吗？",
      answer: "不会。DataBox 的 Engine 运行在本地，数据库驱动、SSH 隧道、SQL 校验和执行都在本地 Engine 内完成。只有模型推理会访问你配置的 OpenAI-compatible Provider。",
      relatedSurface: "security",
    },
    {
      id: "llm-required",
      question: "没有 API Key 能不能使用？",
      answer: "可以使用数据源管理、Schema 浏览和 SQL 控制台等基础能力。问数 Agent 需要配置可用的 LLM Provider，否则会提示先完成配置。",
      relatedSurface: "llm-config",
    },
    {
      id: "dangerous-sql",
      question: "AI 生成了危险 SQL 怎么办？",
      answer: "高风险动作会被策略层和 TrustGate 拦截，进入人工审批。前端会展示风险原因和 SQL 预览，用户确认后才继续。",
      relatedSurface: "approval",
    },
    {
      id: "eval-purpose",
      question: "Agent 评测有什么用？",
      answer: "评测用于验证 Agent 在真实 Schema 下的 SQL 生成、修复和解释能力。它适合作为版本升级、提示词调整和语义层变更后的回归基线。",
      relatedSurface: "agent-eval",
    },
  ],

  navigation: {
    headerTabs: [
      { id: "smart-query", label: "问数", tooltip: "用自然语言生成 SQL、解释结果并继续追问" },
      { id: "datasources", label: "数据源", tooltip: "连接、测试、同步和管理数据库" },
      { id: "sql", label: "SQL", tooltip: "校验、执行、Explain 和查看查询历史" },
      { id: "eval", label: "评测", tooltip: "维护 Agent 评测任务和 benchmark" },
    ],
    commandItems: [
      { id: "open-smart-query", label: "打开问数工作台", hint: "Ask DataBox", action: "open.smartQuery" },
      { id: "open-sql-console", label: "新建 SQL 控制台", hint: "Validate / Execute / Explain", action: "open.sqlConsole" },
      { id: "create-datasource", label: "新建数据源", hint: "MySQL / PostgreSQL / SQLite", action: "open.datasource.create" },
      { id: "open-llm-config", label: "配置 LLM", hint: "OpenAI-compatible Provider", action: "open.llmConfig" },
      { id: "open-agent-eval", label: "打开 Agent 评测", hint: "Run benchmark cases", action: "open.agentEval" },
      { id: "open-history", label: "查看对话历史", hint: "Local conversation records", action: "open.conversationHistory" },
    ],
    toast: {
      datasourceCreated: "数据源已保存，建议立即同步 Schema。",
      datasourceTestOk: "连接测试成功，可以保存该数据源。",
      schemaSynced: "Schema 元数据已同步，Agent 可读取最新上下文。",
      agentWaitingApproval: "该操作存在风险，需要你确认后继续。",
      agentCompleted: "问数完成，结果已保存到本地历史。",
      llmMissingKey: "请先配置 LLM API Key 与模型名称。",
      queryCancelled: "查询已取消，未继续执行后续步骤。",
    },
  },
} as const satisfies ProductAssets;
