#!/usr/bin/env python
"""Build the DBFox Python engine into a standalone sidecar binary.

This script:
  1. Generates a cryptographically random dev token
  2. Writes it to desktop/.env.local (source-mode frontend env)
  3. Builds the engine with PyInstaller inside the .build_venv virtualenv
  4. Copies the binary to desktop/src-tauri/binaries/ with the correct
     target-triplet filename that Tauri's externalBin expects

Usage:
    python build_sidecar.py              # full build
    python build_sidecar.py --token-only # generate token files only
"""

from __future__ import annotations

import argparse
import os
import secrets
import shutil
import subprocess
import sys
from pathlib import Path

from dotenv import dotenv_values
from engine.runtime_paths import private_runtime_file, write_private_text

ROOT = Path(__file__).resolve().parent
ENGINE_DIR = ROOT / "engine"
DESKTOP_DIR = ROOT / "desktop"
BINARIES_DIR = DESKTOP_DIR / "src-tauri" / "binaries"
BUILD_VENV = ROOT / ".build_venv"


def get_target_triplet() -> str:
    """Gets the target triplet for the current platform from rustc, falling back to OS detection."""
    try:
        output = subprocess.check_output(["rustc", "-vV"], text=True)
        for line in output.splitlines():
            if line.startswith("host:"):
                return line.split(":", 1)[1].strip()
    except Exception:
        pass
    
    # Fallback to standard OS and arch mapping
    import platform
    system = platform.system().lower()
    machine = platform.machine().lower()

    arch = "x86_64"
    if "arm" in machine or "aarch64" in machine:
        arch = "aarch64"
    elif "386" in machine or "686" in machine or "i386" in machine or "i686" in machine:
        arch = "i686"
    elif "x86_64" not in machine and "amd64" not in machine:
        print(
            f"  [WARN] Unknown architecture '{machine}' — falling back to x86_64 triplet",
            file=sys.stderr,
        )

    if system == "windows":
        return f"{arch}-pc-windows-msvc"
    elif system == "darwin":
        return f"{arch}-apple-darwin"
    else:
        return f"{arch}-unknown-linux-gnu"

# Must match the dependencies in requirements.txt that PyInstaller
# cannot auto-detect (lazy imports, dynamic loaders, etc.)
HIDDEN_IMPORTS = [
    "uvicorn",
    "sqlalchemy",
    "pydantic",
    "fastapi",
    "watchfiles",
    "alembic",
    "psycopg2",
    "pymysql",
    "sshtunnel",
    "keyring",
    "sqlglot",
    "httpx",
    "cryptography",
    "dotenv",
    "python_multipart",
    "langgraph",
    "langgraph.checkpoint.sqlite",
    "langchain",
    "langchain_openai",
    "langchain_core",
]

LANGSMITH_ENV_KEYS = (
    "LANGCHAIN_TRACING_V2",
    "LANGCHAIN_API_KEY",
    "LANGCHAIN_PROJECT",
    "LANGCHAIN_ENDPOINT",
    "LANGSMITH_TRACING",
    "LANGSMITH_API_KEY",
    "LANGSMITH_PROJECT",
    "LANGSMITH_ENDPOINT",
)


def _venv_python() -> str:
    """Return the python executable inside .build_venv, or fail."""
    if sys.platform == "win32":
        exe = str(BUILD_VENV / "Scripts" / "python.exe")
    else:
        exe = str(BUILD_VENV / "bin" / "python")
    if not Path(exe).exists():
        print(
            f"  [FAIL] 构建虚拟环境未找到: {BUILD_VENV}\n"
            f"  请先创建并安装依赖:\n"
            f"    python -m venv {BUILD_VENV}\n"
            f"    {BUILD_VENV / 'Scripts' / 'pip'} install -r requirements.txt",
            file=sys.stderr,
        )
        sys.exit(1)
    return exe


def generate_token() -> str:
    return secrets.token_hex(32)


def write_env_local(token: str) -> Path:
    path = DESKTOP_DIR / ".env.local"
    path.write_text(
        f"# Generated by build_sidecar.py. Do not edit.\n"
        f'VITE_LOCAL_ENGINE_PORT=18625\n'
        f'VITE_LOCAL_ENGINE_TOKEN="{token}"\n',
        encoding="utf-8",
    )
    print(f"  [OK] {path}")
    return path


def export_langsmith_runtime_env(env_file: Path = ROOT / ".env") -> Path | None:
    if not env_file.exists():
        return None

    values = dotenv_values(env_file)
    lines: list[str] = []
    for key in LANGSMITH_ENV_KEYS:
        value = values.get(key)
        if value:
            lines.append(f"{key}={value}")

    if not lines:
        return None

    target = private_runtime_file("config", "langsmith.env")
    write_private_text(target, "\n".join(lines) + "\n")
    print(f"  [OK] LangSmith runtime env -> {target}")
    return target


def build_pyinstaller(python_exe: str) -> Path:
    dist_dir = ROOT / "pyinstaller_dist"
    work_dir = ROOT / "pyinstaller_build"
    spec_path = ROOT / "dbfox_engine.spec"

    shutil.rmtree(dist_dir, ignore_errors=True)
    shutil.rmtree(work_dir, ignore_errors=True)
    spec_path.unlink(missing_ok=True)

    cmd = [
        python_exe, "-m", "PyInstaller",
        "--onefile",
        "--noconsole",
        "--name", "dbfox-engine",
        "--distpath", str(dist_dir),
        "--workpath", str(work_dir),
        "--add-data", f"{ENGINE_DIR}{os.pathsep}engine",
        "--add-data", f"{ROOT / 'alembic.ini'}{os.pathsep}.",
    ]
    for mod in HIDDEN_IMPORTS:
        cmd += ["--hidden-import", mod]
    cmd.append(str(ENGINE_DIR / "main.py"))

    print("  -> Running PyInstaller (venv: {})...".format(python_exe))
    result = subprocess.run(cmd, cwd=str(ROOT))
    if result.returncode != 0:
        print("  [FAIL] PyInstaller build failed", file=sys.stderr)
        sys.exit(result.returncode)

    built_name = "dbfox-engine.exe" if sys.platform == "win32" else "dbfox-engine"
    built = dist_dir / built_name
    if not built.exists():
        print(f"  [FAIL] Expected binary not found: {built}", file=sys.stderr)
        sys.exit(1)

    size_mb = built.stat().st_size / 1_048_576
    print(f"  [OK] Built {size_mb:.0f} MB binary")
    return built


def install_sidecar(binary: Path) -> Path:
    BINARIES_DIR.mkdir(parents=True, exist_ok=True)
    triplet = get_target_triplet()
    name = f"dbfox-engine-{triplet}"
    if sys.platform == "win32":
        name += ".exe"
    dest = BINARIES_DIR / name
    shutil.copy2(binary, dest)
    print(f"  [OK] Sidecar -> {dest}")
    return dest


def main() -> None:
    parser = argparse.ArgumentParser(description="Build DBFox engine sidecar")
    parser.add_argument(
        "--token-only",
        action="store_true",
        help="Only generate token files, skip PyInstaller build",
    )
    args = parser.parse_args()

    print("=" * 55)
    print("DBFox Sidecar Builder")
    print("=" * 55)

    token = generate_token()
    print(f"\n[1/3] Dev token ({len(token)} hex chars)")
    write_env_local(token)
    export_langsmith_runtime_env()

    if args.token_only:
        print("\n  Done (token-only mode).")
        return

    python_exe = _venv_python()
    print(f"\n[2/3] PyInstaller build")
    binary = build_pyinstaller(python_exe)

    print("\n[3/3] Install to Tauri binaries")
    dest = install_sidecar(binary)

    shutil.rmtree(ROOT / "pyinstaller_dist", ignore_errors=True)
    shutil.rmtree(ROOT / "pyinstaller_build", ignore_errors=True)
    (ROOT / "dbfox_engine.spec").unlink(missing_ok=True)

    print("\n" + "=" * 55)
    print("Sidecar build complete.")
    print(f"  {dest}")
    print("  Next: cd desktop && npm run tauri -- build")
    print("=" * 55)


if __name__ == "__main__":
    main()
