"""Dedicated table-preview executor for the Workbench.

Produces a backend-generated SELECT … LIMIT … query, enforces
limits, and returns structured results — never exposes TrustGate
internals to the user.
"""
from __future__ import annotations

import logging
import time
import uuid
from typing import Any

from sqlalchemy.orm import Session

from engine.models import DataSource, SchemaTable

logger = logging.getLogger("databox.workbench.table_preview")

MAX_PREVIEW_ROWS = 1000
DEFAULT_PREVIEW_ROWS = 100


def execute_table_preview(
    db: Session,
    datasource_id: str,
    table_name: str,
    limit: int = DEFAULT_PREVIEW_ROWS,
) -> dict[str, Any]:
    """Run a safe table-preview query.

    - SQL is generated by the backend (not user-controlled).
    - *table_name* must exist in the SchemaTable catalog.
    - LIMIT is enforced and clamped to MAX_PREVIEW_ROWS.
    - Single-table SELECT only.
    """
    # 1. Validate datasource
    ds = db.query(DataSource).filter(DataSource.id == datasource_id).first()
    if ds is None:
        return {
            "status": "error",
            "error_code": "DATASOURCE_NOT_FOUND",
            "message": "数据源未找到。",
        }

    # 2. Validate table name against catalog
    schema_table = (
        db.query(SchemaTable)
        .filter(
            SchemaTable.data_source_id == datasource_id,
            SchemaTable.table_name == table_name,
        )
        .first()
    )
    if schema_table is None:
        return {
            "status": "error",
            "error_code": "TABLE_NOT_IN_CATALOG",
            "message": f"表 '{table_name}' 不在系统 Catalog 中，无法预览。请先同步 Schema。",
        }

    # 3. Clamp limit
    clamped_limit = max(1, min(int(limit), MAX_PREVIEW_ROWS))

    # 4. Generate backend-controlled SQL — never accepts arbitrary SQL from frontend
    dialect = (ds.db_type or "mysql").lower()
    if "postgres" in dialect:
        sql = f'SELECT * FROM "{table_name}" LIMIT {clamped_limit}'
    else:
        sql = f"SELECT * FROM `{table_name}` LIMIT {clamped_limit}"

    # 5. Execute with table_preview policy
    from engine.executor import execute_query
    from engine.policy.engine import PolicyEngine

    # Policy check (table_preview — skips AST parsing)
    PolicyEngine.enforce_query_policy(ds, sql, policy="table_preview")

    # Execute with table_preview policy
    start = time.perf_counter()
    try:
        result = execute_query(
            db=db,
            datasource_id=datasource_id,
            sql_str=sql,
            question=f"[Workbench] Preview table: {table_name}",
            bypass_guardrail=False,
            safety_policy="table_preview",  # type: ignore[arg-type]
        )
    except Exception as exc:
        latency_ms = int((time.perf_counter() - start) * 1000)
        logger.warning("Table preview failed for %s.%s: %s", datasource_id, table_name, exc)
        return {
            "status": "error",
            "error_code": "EXECUTION_FAILED",
            "message": f"数据预览执行失败: {str(exc)[:200]}",
            "latency_ms": latency_ms,
        }

    latency_ms = int((time.perf_counter() - start) * 1000)

    env = (ds.env or "dev").lower()
    return {
        "status": "success",
        "policy": "table_preview",
        "datasource_env": env,
        "datasource_name": ds.name,
        "table_name": table_name,
        "limit": clamped_limit,
        "columns": result.get("columns", []),
        "rows": result.get("rows", []),
        "row_count": result.get("rowCount", 0),
        "redacted_columns": [],
        "latency_ms": latency_ms,
        "audit_id": result.get("historyId", ""),
        "environment_note": (
            "PROD 数据源 · 已限制行数 · 已记录审计"
            if env == "prod"
            else None
        ),
    }
