from __future__ import annotations

from typing import Annotated, Any, Literal, TypedDict

from langgraph.graph.message import add_messages


# Reducer for append-only lists (artifacts, trace_events, runtime_events).
# messages uses its own add_messages reducer from LangGraph.
def _add_list(left: list[Any], right: list[Any]) -> list[Any]:
    if not right:
        return left
    if isinstance(right[0], dict) and right[0].get("__clear__"):
        return right[1:]
    return left + right


AgentStatus = Literal[
    "running",
    "waiting_approval",
    "waiting_user",
    "completed",
    "failed",
]


class DBFoxAgentState(TypedDict, total=False):
    # =========================================================================
    # 1. CORE & IDENTITY STATE
    # =========================================================================
    messages: Annotated[list[Any], add_messages]
    """LangGraph message history containing Human, AI, and Tool messages."""

    run_id: str
    """Unique UUID for this specific execution run."""
    thread_id: str
    """LangGraph thread/session ID for state checkpointing."""
    session_id: str
    """Active session ID mirroring the frontend's conversation ID."""
    datasource_id: str
    """The database datasource ID to compile and execute SQL queries against."""
    user_id: str | None
    """Optional user identifier associated with the session."""
    project_id: str | None
    """Optional workspace project ID."""
    parent_run_id: str | None
    """Parent run ID if this is a resumed or follow-up execution."""

    execute: bool
    """Whether the agent is permitted to execute write/read queries on the DB."""
    max_steps: int
    """Maximum number of iterations allowed for the ReAct loop."""
    step_count: int
    """Current step iteration index."""
    status: AgentStatus
    """Terminal or transient status (running, waiting_approval, completed, etc.)."""
    error: str | None
    """Runtime error message if the run failed."""
    last_error_telemetry: dict[str, Any] | None
    """Detailed telemetry payload for the last occurred error."""

    # =========================================================================
    # 2. DB CONTEXT & SEMANTIC METADATA
    # =========================================================================
    environment_profile: dict[str, Any] | None
    """Basic operating system/environment profiling."""
    database_map: dict[str, Any] | None
    """Static db schema structural map (tables, columns, types)."""
    semantic_resolution: dict[str, Any] | None
    """Resolved semantic vocabulary, aliases, and metrics from the Semantic Layer."""
    db_search_results: dict[str, Any] | None
    """Output from database metadata keyword searches."""
    db_inspection: dict[str, Any] | None
    """Detailed table/column schema inspection results."""
    db_preview: dict[str, Any] | None
    """Table data sample previews fetched from datasource."""
    workspace_context: dict[str, Any] | None
    """Active UI context (tabs, selection states, editor annotations)."""
    follow_up_context: dict[str, Any] | None
    """Prior messages and artifacts from preceding runs to maintain context."""
    context_pack: dict[str, Any] | None
    """Agent v2 consolidated metadata pack sent to the LLM and the frontend."""
    context_summary: str | None
    """Human-readable summary of the active datasource, workspace, and linked schema context."""

    # ── Large Catalog Exploration State ──
    candidate_tables: list[str]
    """Pool of table names discovered through search/expand that are candidates for the current question.

    Populated by db.search, schema.list_tables_page, and schema.expand_related_tables.
    Used by the model to track which tables are relevant without re-searching.
    """
    searched_terms: Annotated[list[str], _add_list]
    """Set of search queries already executed (lowercased, deduped before search).

    Prevents the agent from repeating the same keyword search across steps.
    The observe_node normalizes and deduplicates entries before appending.
    """
    exhausted_paths: Annotated[list[str], _add_list]
    """Tool+argument signatures that returned empty or failed results.

    Format: ``{tool_name}::{arg_signature}`` (e.g. ``db.search::cookie``,
    ``schema.describe_table::users_archive``).  The loop prevention fast-path
    uses this to short-circuit retries before they happen.
    """

    # =========================================================================
    # 3. SQL GENERATION & SAFETY GATE
    # =========================================================================
    schema_context: dict[str, Any] | None
    """Active schema metadata compiled for model prompting."""
    schema_metadata: dict[str, Any] | None
    """Extra metadata properties for table relationships and indexes."""
    query_plan: dict[str, Any] | None
    """Step-by-step query blueprint generated by the agent."""
    sql_candidate: dict[str, Any] | None
    """The raw SQL query proposed by the LLM."""
    sql: str | None
    """The verified/validated SQL query ready for execution."""
    safety: dict[str, Any] | None
    """Output from the Policy/Trust gate (can_execute, risks, reasons)."""
    execution: dict[str, Any] | None
    """Results of SQL execution (success status, row count, error info)."""
    chart_suggestion: dict[str, Any] | None
    """Auto-generated suggestion for rendering result charts."""
    suggestions: Annotated[list[dict[str, Any]], _add_list]
    """Follow-up questions or actions suggested by the agent.

    Uses ``_add_list`` reducer so that multiple nodes can append suggestions
    concurrently without data loss.  To replace all suggestions atomically,
    include ``{"__clear__": True}`` as the first element of the update.
    """

    # ── Multi-query Analysis Units (P1) ──
    analysis_units: Annotated[list[dict[str, Any]], _add_list]
    """Accumulated query execution results, one per distinct SQL statement.

    Each successful ``sql.execute_readonly`` appends a new unit.  Subsequent
    ``chart.suggest`` calls enrich the matching unit
    (keyed by SQL fingerprint).  The final ``answer.synthesize`` can consume
    all units instead of only the latest execution.
    """
    current_analysis_unit_id: str | None
    """SQL fingerprint of the most recently executed query, used to match
    profile/chart results to the correct analysis unit."""
    answer: dict[str, Any] | None
    """Synthesized final response to the user's question."""
    final_answer: dict[str, Any] | None
    """Historical duplicate key for synthesis answer."""

    # =========================================================================
    # 4. TOOL ROUTING & POLICIES
    # =========================================================================
    pending_tool_calls: list[dict[str, Any]]
    """Tool calls requested by the model but not yet executed."""
    allowed_tool_calls: list[dict[str, Any]]
    """Tool calls that cleared safety checks and are allowed to execute."""
    blocked_tool_calls: list[dict[str, Any]]
    """Tool calls blocked by the PolicyGate."""
    last_tool_results: list[dict[str, Any]]
    """Outputs from the most recently executed batch of tools."""
    last_observation: dict[str, Any] | None
    """Observation string returned from tool execution for model consumption."""
    last_tool_name: str | None
    """Name of the last tool invoked."""
    last_tool_metadata: dict[str, Any] | None
    """Metadata tags associated with the last tool call."""

    # =========================================================================
    # 5. HUMAN-IN-THE-LOOP & APPROVALS
    # =========================================================================
    pending_approval: dict[str, Any] | None
    """The active approval request if the graph is interrupted waiting for user consent."""
    approval_result: dict[str, Any] | None
    """The user's response to the approval request (approved/rejected)."""

    # =========================================================================
    # 6. REVISION & REPAIR STATE
    # =========================================================================
    revision_attempted: bool
    """Flag indicating whether a SQL query correction step has been tried."""
    revision_count: int
    """Number of query revisions attempted during execution."""
    repair_mode: bool
    """True if the agent is actively executing error correction/repair nodes."""
    repair_stats: dict[str, Any] | None
    """Performance and attempt metrics of the query repair loop."""
    repair_trace: Annotated[list[dict[str, Any]], _add_list]
    """Trace logs of the repair steps taken."""

    # =========================================================================
    # 7. PROGRESS & LOOP CONTROL
    # =========================================================================
    progress_decision: dict[str, Any] | None
    """Evaluation verdict from the Progress Judge node."""
    replan_count: int
    """Counter tracking consecutive replan loop iterations."""
    consecutive_blocks: int
    """Counter for tracking sequential policy violations to abort infinite loops."""
    tool_call_history: Annotated[list[dict[str, Any]], _add_list]
    """History of executed tool calls for loop prevention."""

    # =========================================================================
    # 8. PERSISTENCE COLLECTIONS & UI COMPATIBILITY
    # =========================================================================
    artifacts: Annotated[list[dict[str, Any]], _add_list]
    """Collects rich user-facing cards (SQL code, tables, charts, insights)."""
    trace_events: Annotated[list[dict[str, Any]], _add_list]
    """Underlying step-by-step trace events for debugging."""
    runtime_events: Annotated[list[dict[str, Any]], _add_list]
    """Yielded user-facing events streamed via Server-Sent Events (SSE)."""
    plan_events: Annotated[list[dict[str, Any]], _add_list]
    """[UI Compatibility] Sequence of plans or step-status changes for frontend rendering."""
    plan_directive: dict[str, Any] | None
    """[UI/Eval Compatibility] Legacy planner output directing allowed tool groups."""
    execution_mode: str
    """[UI/Eval Compatibility] Legacy planner direction for tool usage mode."""
    allowed_tool_groups: list[str]
    """[UI/Eval Compatibility] Tool namespaces the agent is permitted to query."""
    selected_skill_ids: list[str]
    """[UI/Eval Compatibility] List of registered custom agent skills active in this context."""

    # =========================================================================
    # 9. NAMESPACED STATE PROJECTIONS
    # =========================================================================
    run: dict[str, Any]
    """RunState projection: IDs, status, execution budget, and terminal error."""
    working: dict[str, Any]
    """WorkingMemoryState projection: context, semantic/schema/SQL, progress, and repair fields."""
    tools: dict[str, Any]
    """ToolExchangeState projection: pending/allowed/blocked calls, results, and policy controls."""
    ui: dict[str, Any]
    """PresentationState projection: artifacts, runtime/trace events, and user-visible summaries."""


_RUN_NAMESPACE_KEYS = (
    "run_id",
    "thread_id",
    "session_id",
    "datasource_id",
    "parent_run_id",
    "execute",
    "max_steps",
    "step_count",
    "status",
    "error",
)

_WORKING_NAMESPACE_KEYS = (
    "environment_profile",
    "database_map",
    "semantic_resolution",
    "db_search_results",
    "db_inspection",
    "db_preview",
    "workspace_context",
    "follow_up_context",
    "context_pack",
    "context_summary",
    "candidate_tables",
    "searched_terms",
    "exhausted_paths",
    "schema_context",
    "schema_metadata",
    "query_plan",
    "sql_candidate",
    "sql",
    "safety",
    "execution",
    "chart_suggestion",
    "suggestions",
    "analysis_units",
    "current_analysis_unit_id",
    "answer",
    "final_answer",
    "revision_attempted",
    "revision_count",
    "repair_mode",
    "repair_stats",
    "repair_trace",
    "progress_decision",
    "replan_count",
    "consecutive_blocks",
)

_TOOLS_NAMESPACE_KEYS = (
    "pending_tool_calls",
    "allowed_tool_calls",
    "blocked_tool_calls",
    "last_tool_results",
    "last_observation",
    "last_tool_name",
    "last_tool_metadata",
    "pending_approval",
    "approval_result",
    "tool_call_history",
    "plan_directive",
    "execution_mode",
    "allowed_tool_groups",
    "selected_skill_ids",
)

_UI_NAMESPACE_KEYS = (
    "artifacts",
    "trace_events",
    "runtime_events",
    "plan_events",
    "visible_plan",
    "context_summary",
)


def sync_state_namespaces(state: dict[str, Any]) -> dict[str, Any]:
    """Refresh namespaced state projections from the flat LangGraph state.

    The flat fields remain the authoritative compatibility layer while nodes are
    migrated gradually. These projections make state diffs readable and give new
    code a stable sectioned contract to consume.
    """
    state["run"] = _project_namespace(state, _RUN_NAMESPACE_KEYS)
    state["working"] = _project_namespace(state, _WORKING_NAMESPACE_KEYS)
    state["tools"] = _project_namespace(state, _TOOLS_NAMESPACE_KEYS)
    state["ui"] = _project_namespace(state, _UI_NAMESPACE_KEYS)
    return state


def _project_namespace(state: dict[str, Any], keys: tuple[str, ...]) -> dict[str, Any]:
    return {key: _project_value(state.get(key)) for key in keys if key in state}


def _project_value(value: Any) -> Any:
    if isinstance(value, list) and value and isinstance(value[0], dict) and value[0].get("__clear__"):
        return list(value[1:])
    return value
